### ISSUE TITLE
Sortierung für Artikel Variante hinzufügen

### ISSUE THREAD

**Issue by hauptmedia** [remedyMatch/rm-backend#11]
integer, welches die Sortierreihenfolge angibt, damit im Frontend danach sortiert werden kann

**Comment by matusmala** [comment]
Nicht nach Namen?

**Comment by marcoebbinghaus** [comment]
Geht ja erstmal nur um die Initial-Daten oder? Ich würde die numerische Sortierung für diese auf jeden Fall erstmal lexikongraphisch nach Namen vergeben im Rahmen dieses Tickets.

**Comment by hauptmedia** [comment]
Naja es geht um die Größen für Kittel: XS, S, M, L, XL, XXL oder was es da gibt, das muss logisch nach Größe sortiert werden

**Comment by marcoebbinghaus** [comment]
jo, alles klar.

**Comment by marcoebbinghaus** [comment]
Ist fertig. Zusätzlich zum nun mitgelieferten "sort" field (nullable) in den ArtikelVarianten, liefert das backend diese auch schon direkt nach dem sort field sortiert (Varianten mit sort value = null kommen zum Schluss und sind sortiert nach Varianten-Name), sodass im Frontend hierfür nichts angepasst werden muss.
