### ISSUE TITLE
Standort optimieren (Persistenz)

### ISSUE THREAD

**Issue by marcoebbinghaus** [remedyMatch/rm-backend#7]
Wir speichern den Standort derzeit als einfache Strings in verschiedenen Entitäten.
Ensprechend bieten wir in der GUI auch lediglich ein Textfeld zur Eingabe des Standorts an.

Stand jetzt speichern wir den Standort für die unterschiedlichen Entitäten folgendermaßen:

- anfrage_entity: standort_an @Column --> varchar(255), @Column --> standort_von varchar(255)
- angebot_entity: @Column(length = 60) --> standort varchar(60)
- bedarf_entity: standort @Column(length = 60) --> varchar(60)
- institution_entity: standort @Column --> varchar(255)
- match_entity: standort_an @Column --> varchar(255), standort_von @Column --> varchar(255)

Umsetzungssvorschläge: 

- Geokoordinaten auf DB-Ebene?
- Möglicherweise erstmal die Eingabe aus dem Standort (Adresse?)-Textfeld nehmen, mittels API (google? maps?) versuchen, daraus Geokoordinaten zu machen und diese weg zu speichern? Wir könnten die Adresseeingabe und die Geokoordinaten parallel speichern um in der GUI (weiterhin) nur die Benutzereingabe anzuzeigen, aber trotzdem genaue Koordinaten haben die wir dann im Logistik-Kontext verwenden können. Nachteil: Benutzer sieht die zur Eingabe gefundenen Geokoordinaten nicht und kann sie so auch nicht korrigieren. Was passiert wenn eine Eingabe nicht zu Geokoordinaten aufgelöst werden kann?

**Comment by hauptmedia** [comment]
GEO Koordinaten brauchen wir ja zwingend für die Umkreissuche. Ist nur die Frage wie am elegantesten die Adressdaten in GEO points umsetzen können. Entweder es gibt einen Backend Service der das macht (Vorschläge bei Ortseingabe) oder das ist eine Funktionalität vom Frontend und es wird nur der Point übertragen.

**Comment by matusmala** [comment]
Hast du nicht bereits die GEO Kordinaten da?

**Comment by marcoebbinghaus** [comment]
Ich habe inzwischen einen Geocoder im Backend angebunden und einen entsprechenden Service/Controller implementiert. Was fehlt ist, dass die GUI die Funktionalität nutzt (z.B. um bei Eingabe eines Standorts vollständige Adressvorschläge anzubieten).
